### ISSUE TITLE
Binding cannot be changed after it has been used.

### ISSUE THREAD

**Issue by gurgen1982** [XAMLMarkupExtensions/WPFLocalizationExtension#204]
Hi. I have the following code in xaml
<UserControl....
**xmlns:lex="http://wpflocalizeextension.codeplex.com"
lex:ResxLocalizationProvider.DefaultAssembly="[my_assembly_name]"
lex:ResxLocalizationProvider.DefaultDictionary="Resources.Resources"**
/>

Then use it in markup like this
<dxr:RibbonPage x:Name="Pages_Home" Caption="**{Binding Source={lex:Loc RibbonTitle}}**">
</dxr:RibbonPage>

It show the localized caption correctly, but when I try to change the localization like this

var culture = new System.Globalization.CultureInfo(_code);
System.Threading.Thread.CurrentThread.CurrentCulture = culture;
System.Threading.Thread.CurrentThread.CurrentUICulture = culture;
**WPFLocalizeExtension.Engine.LocalizeDictionary.Instance.Culture = culture;**

I get the error on the last row.
So how can I proceed with this part of code  ??

The stack trace is:

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.SetPropertyValue(Object value, TargetInfo info, Boolean forceNull)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.DictionaryEvent.Invoke(DependencyObject sender, DictionaryEventArgs args)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.set_Culture(CultureInfo value)

**Comment by wowfood** [comment]
Try using

LocalizeDictionary.Instance.SetCultureCommand.Execute( cultureName );

instead

**Comment by gurgen1982** [comment]
> Try using
> 
> LocalizeDictionary.Instance.SetCultureCommand.Execute( cultureName );
> 
> instead

Still the same error message

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.SetPropertyValue(Object value, TargetInfo info, Boolean forceNull)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at XAMLMarkupExtensions.Base.NestedMarkupExtension.UpdateNewValue(TargetPath targetPath)
   at WPFLocalizeExtension.Extensions.LocExtension.ResourceChanged(DependencyObject sender, DictionaryEventArgs e)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.DictionaryEvent.Invoke(DependencyObject sender, DictionaryEventArgs args)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.set_Culture(CultureInfo value)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.SetCulture(CultureInfo c)
   at WPFLocalizeExtension.Engine.LocalizeDictionary.CultureInfoDelegateCommand.Execute(Object parameter)
   at ...

**Comment by konne** [comment]
This is a binding class issue and not an issue of this library.
